"""Time series forecasting that picks its model by what would have worked.

``foresight`` fits several models to a series, replays the past to see how
each would have done (a rolling-origin backtest), chooses by out-of-sample
error and reports intervals taken from the errors actually observed,
including intervals for the total of the next k periods.

The models, the backtest and the utilities are the Rust crate ``foresight``
(https://crates.io/crates/foresight), compiled into this package: the
numbers are the crate's, and the backtest runs on all cores.

>>> import foresight as fs
>>> y = fs.monthly(values, first_month=3)        # doctest: +SKIP
>>> report = fs.backtest(y)                      # doctest: +SKIP
>>> report.best.name, report.best.forecast[0]    # doctest: +SKIP
"""

from ._foresight import (
    CRATE_VERSION,
    Arima,
    AutoArima,
    AutoEts,
    Candidate,
    Croston,
    Decomposed,
    Decomposition,
    Drift,
    Ensemble,
    Ets,
    Fit,
    HoltWinters,
    LogLinear,
    Mean,
    Model,
    Naive,
    Outlier,
    Point,
    Prophet,
    Regressors,
    Report,
    SeasonalNaive,
    Series,
    Tbats,
    Theta,
    Transformed,
    __version__,
    acf,
    backtest,
    bias,
    box_cox,
    clean,
    defaults,
    difference,
    guerrero,
    interpolate,
    inv_box_cox,
    kpss,
    log,
    mae,
    mape,
    mase,
    max_threads,
    monthly,
    mstl,
    ndiffs,
    nsdiffs,
    outliers,
    quarterly,
    rmse,
    seasonal_strength,
    set_max_threads,
    stl,
    thorough,
)

__all__ = [
    "CRATE_VERSION",
    "Arima",
    "AutoArima",
    "AutoEts",
    "Candidate",
    "Croston",
    "Decomposed",
    "Decomposition",
    "Drift",
    "Ensemble",
    "Ets",
    "Fit",
    "HoltWinters",
    "LogLinear",
    "Mean",
    "Model",
    "Naive",
    "Outlier",
    "Point",
    "Prophet",
    "Regressors",
    "Report",
    "SeasonalNaive",
    "Series",
    "Tbats",
    "Theta",
    "Transformed",
    "__version__",
    "acf",
    "backtest",
    "bias",
    "box_cox",
    "clean",
    "defaults",
    "difference",
    "guerrero",
    "interpolate",
    "inv_box_cox",
    "kpss",
    "log",
    "mae",
    "mape",
    "mase",
    "max_threads",
    "monthly",
    "mstl",
    "ndiffs",
    "nsdiffs",
    "outliers",
    "quarterly",
    "rmse",
    "seasonal_strength",
    "set_max_threads",
    "stl",
    "thorough",
]
