from typing import Any, Iterable, Optional, Sequence, Union, final

_Numbers = Union["Series", Iterable[Optional[float]]]

__version__: str
CRATE_VERSION: str

@final
class Series:
    def __new__(cls, values: Iterable[Optional[float]], period: int = 1, first_season: int = 1) -> Series: ...
    @property
    def values(self) -> list[float]: ...
    @property
    def period(self) -> int: ...
    @property
    def first_season(self) -> int: ...
    def __len__(self) -> int: ...

def monthly(values: Iterable[Optional[float]], first_month: int = 1) -> Series: ...
def quarterly(values: Iterable[Optional[float]], first_quarter: int = 1) -> Series: ...

@final
class Fit:
    @property
    def model(self) -> str: ...
    def forecast(self, h: int) -> list[float]: ...
    @property
    def params(self) -> dict[str, float]: ...
    @property
    def log_likelihood(self) -> Optional[float]: ...
    @property
    def aic(self) -> Optional[float]: ...
    @property
    def aicc(self) -> Optional[float]: ...
    @property
    def bic(self) -> Optional[float]: ...
    @property
    def residuals(self) -> Optional[list[float]]: ...
    @property
    def details(self) -> dict[str, Any]: ...

class Model:
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    def named(self, name: str, description: Optional[str] = None) -> Model: ...
    def fit(self, y: _Numbers, period: Optional[int] = None) -> Fit: ...
    def forecast(self, y: _Numbers, h: int, period: Optional[int] = None) -> list[float]: ...

@final
class Mean(Model):
    def __new__(cls) -> Mean: ...

@final
class Naive(Model):
    def __new__(cls) -> Naive: ...

@final
class Drift(Model):
    def __new__(cls) -> Drift: ...

@final
class SeasonalNaive(Model):
    def __new__(cls, growth: bool = False) -> SeasonalNaive: ...

@final
class Theta(Model):
    def __new__(cls) -> Theta: ...

@final
class HoltWinters(Model):
    def __new__(cls) -> HoltWinters: ...

@final
class LogLinear(Model):
    def __new__(cls, window: Optional[int] = None, deflator: Optional[Iterable[float]] = None) -> LogLinear: ...

@final
class Regressors:
    def __new__(cls, columns: Optional[dict[str, Iterable[float]]] = None) -> Regressors: ...
    @staticmethod
    def fourier(period: float, order: int, rows: int) -> Regressors: ...
    @staticmethod
    def seasonal_dummies(period: int, rows: int) -> Regressors: ...
    def __add__(self, other: Regressors, /) -> Regressors: ...
    @property
    def names(self) -> list[str]: ...
    @property
    def rows(self) -> int: ...

@final
class Arima(Model):
    def __new__(
        cls,
        order: tuple[int, int, int] = ...,
        seasonal: Optional[tuple[int, int, int]] = None,
        constant: Optional[bool] = None,
        regressors: Optional[Regressors] = None,
    ) -> Arima: ...
    @staticmethod
    def airline() -> Arima: ...

@final
class AutoArima(Model):
    def __new__(
        cls,
        criterion: str = "aicc",
        d: Optional[int] = None,
        seasonal_d: Optional[int] = None,
        max_order: Optional[tuple[int, int, int, int]] = None,
        regressors: Optional[Regressors] = None,
    ) -> AutoArima: ...

@final
class Ets(Model):
    def __new__(cls, code: str) -> Ets: ...

@final
class AutoEts(Model):
    def __new__(cls, criterion: str = "aicc") -> AutoEts: ...

@final
class Prophet(Model):
    def __new__(
        cls,
        changepoints: Optional[int] = None,
        changepoint_range: Optional[float] = None,
        changepoint_prior_scale: Optional[float] = None,
        seasonality_prior_scale: Optional[float] = None,
        fourier_order: Optional[int] = None,
        event_prior_scale: Optional[float] = None,
        events: Optional[Union[dict[str, Sequence[int]], Sequence[tuple[str, Sequence[int]]]]] = None,
        steps: Optional[Union[dict[str, int], Sequence[tuple[str, int]]]] = None,
    ) -> Prophet: ...

@final
class Tbats(Model):
    def __new__(
        cls,
        periods: Optional[Sequence[float]] = None,
        harmonics: Optional[Sequence[int]] = None,
        box_cox: Optional[bool] = None,
        trend: Optional[bool] = None,
        damped: Optional[bool] = None,
        arma_errors: Optional[bool] = None,
        arma_orders: Optional[tuple[int, int]] = None,
    ) -> Tbats: ...

@final
class Croston(Model):
    def __new__(
        cls,
        variant: str = "croston",
        alpha: Optional[float] = None,
        beta: Optional[float] = None,
        optimised: bool = False,
    ) -> Croston: ...

@final
class Decomposed(Model):
    def __new__(cls, model: Model, periods: Optional[Sequence[int]] = None, robust: bool = False) -> Decomposed: ...

@final
class Ensemble(Model):
    def __new__(
        cls,
        members: Sequence[Model],
        weighting: str = "inverse_error",
        origins: Optional[int] = None,
        horizon: Optional[int] = None,
        top: Optional[int] = None,
    ) -> Ensemble: ...

@final
class Transformed(Model):
    def __new__(cls, model: Model, lam: Optional[Union[float, str]] = None) -> Transformed: ...

def log(model: Model) -> Transformed: ...
def defaults() -> list[Model]: ...
def thorough() -> list[Model]: ...

@final
class Point:
    @property
    def horizon(self) -> int: ...
    @property
    def mean(self) -> float: ...
    @property
    def intervals(self) -> dict[float, tuple[float, float]]: ...
    def interval(self, level: float) -> tuple[float, float]: ...

@final
class Candidate:
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def components(self) -> list[str]: ...
    @property
    def score(self) -> float: ...
    @property
    def params(self) -> dict[str, float]: ...
    @property
    def horizons(self) -> list[dict[str, Any]]: ...
    @property
    def trajectories(self) -> list[list[float]]: ...
    @property
    def forecast(self) -> list[Point]: ...
    def cumulative(self, k: int) -> Point: ...
    def to_pandas(self) -> Any: ...

@final
class Report:
    @property
    def candidates(self) -> list[Candidate]: ...
    @property
    def best(self) -> Candidate: ...
    @property
    def chosen(self) -> int: ...
    @property
    def origins(self) -> int: ...
    @property
    def first_origin(self) -> int: ...
    @property
    def horizon(self) -> int: ...
    @property
    def metric(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, str], /) -> Candidate: ...
    def to_pandas(self) -> Any: ...

def backtest(
    y: _Numbers,
    candidates: Optional[Sequence[Model]] = None,
    *,
    period: Optional[int] = None,
    origins: int = 36,
    horizon: int = 12,
    min_train: int = 48,
    window: Optional[int] = None,
    combine: int = 2,
    levels: Sequence[float] = ...,
    metric: str = "mape",
    parallel: bool = True,
) -> Report: ...

@final
class Decomposition:
    @property
    def periods(self) -> list[int]: ...
    @property
    def trend(self) -> list[float]: ...
    @property
    def seasonal(self) -> list[list[float]]: ...
    @property
    def remainder(self) -> list[float]: ...
    @property
    def seasonally_adjusted(self) -> list[float]: ...
    @property
    def trend_strength(self) -> float: ...
    def seasonal_strength(self, i: int = 0) -> float: ...
    def to_pandas(self) -> Any: ...

def stl(
    y: _Numbers,
    period: int,
    seasonal_window: Optional[int] = None,
    *,
    trend_window: Optional[int] = None,
    low_pass_window: Optional[int] = None,
    degrees: Optional[tuple[int, int, int]] = None,
    robust: bool = False,
    inner: Optional[int] = None,
    outer: Optional[int] = None,
) -> Decomposition: ...
def mstl(
    y: _Numbers,
    periods: Sequence[int],
    *,
    windows: Optional[Sequence[int]] = None,
    iterations: Optional[int] = None,
    robust: bool = False,
) -> Decomposition: ...

@final
class Outlier:
    @property
    def index(self) -> int: ...
    @property
    def value(self) -> float: ...
    @property
    def replacement(self) -> float: ...

def interpolate(values: _Numbers, period: int = 1) -> list[float]: ...
def outliers(values: _Numbers, period: int = 1) -> list[Outlier]: ...
def clean(values: _Numbers, period: int = 1) -> list[float]: ...
def acf(y: _Numbers, max_lag: int) -> list[float]: ...
def difference(y: _Numbers, lag: int = 1) -> list[float]: ...
def kpss(y: _Numbers) -> Optional[float]: ...
def ndiffs(y: _Numbers, max: int = 2) -> int: ...
def nsdiffs(y: _Numbers, period: int) -> int: ...
def seasonal_strength(y: _Numbers, period: int) -> Optional[float]: ...
def box_cox(y: _Numbers, lam: float) -> list[float]: ...
def inv_box_cox(z: _Numbers, lam: float) -> list[float]: ...
def guerrero(y: _Numbers, period: Optional[int] = None) -> float: ...
def mape(actual: _Numbers, forecast: _Numbers) -> Optional[float]: ...
def bias(actual: _Numbers, forecast: _Numbers) -> Optional[float]: ...
def mae(actual: _Numbers, forecast: _Numbers) -> Optional[float]: ...
def rmse(actual: _Numbers, forecast: _Numbers) -> Optional[float]: ...
def mase(actual: _Numbers, forecast: _Numbers, train: _Numbers, period: int = 1) -> Optional[float]: ...
